-- ============================================================================
-- AMS-FaceRec — Final Consolidated Database Schema
-- ============================================================================
-- This file represents the COMPLETE current state of the database after all
-- migrations have been applied. It is the single source of truth.
--
-- Migration history (in order):
--   1. schema.sql                          — Original base schema
--   2. add_profile_fields.sql              — Extended profiles with name/phone/etc.
--   3. add_approval_status.sql             — Added approval workflow
--   4. 20260516_add_registration_fields.sql — Registration & face enrollment fields
--   5. 20260519_add_timetable_entries.sql   — Timetable entries + course source_key
--   6. 20260520_update_domain_model.sql     — Renamed department→branch, section→session
--   7. 20260520_seed_demo_data.sql          — Demo data (not included here — see seed file)
--   8. 20260521_db_restructure_step1.sql    — Unified users table + extension tables
--
-- Safe to run: Uses IF NOT EXISTS / ON CONFLICT everywhere.
-- Run in: Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- ============================================================================


-- ════════════════════════════════════════════════════════════════════════════
-- 1. ENUMS & TYPES
-- ════════════════════════════════════════════════════════════════════════════

DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'teacher', 'student');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;


-- ════════════════════════════════════════════════════════════════════════════
-- 2. BASE TABLES
-- ════════════════════════════════════════════════════════════════════════════

-- ── 2.1 Users (unified identity — replaces profiles + students + instructors) ─

CREATE TABLE IF NOT EXISTS public.users (
    id               UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    role             user_role NOT NULL,
    email            TEXT NOT NULL UNIQUE,
    full_name        TEXT NOT NULL,
    phone            TEXT,
    avatar_url       TEXT,
    branch           TEXT,
    approval_status  TEXT NOT NULL DEFAULT 'approved'
                     CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    is_active        BOOLEAN NOT NULL DEFAULT true,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  public.users IS 'Single source of truth for every person in the system (admin, teacher, student).';
COMMENT ON COLUMN public.users.approval_status IS 'pending = awaiting admin review, approved = can log in, rejected = access denied.';
COMMENT ON COLUMN public.users.is_active IS 'Soft-delete flag. Inactive users cannot log in.';


-- ── 2.2 Student Details (extension for role = student) ──────────────────────

CREATE TABLE IF NOT EXISTS public.student_details (
    user_id           UUID REFERENCES public.users(id) ON DELETE CASCADE PRIMARY KEY,
    sbrn              TEXT NOT NULL UNIQUE,         -- Student Board Roll Number (e.g. 2024CE001)
    semester          INTEGER NOT NULL CHECK (semester BETWEEN 1 AND 8),
    session           TEXT NOT NULL,                -- Academic session (e.g. 2024 - 2027)
    section           TEXT,
    registration_date DATE DEFAULT CURRENT_DATE,
    attendance_rate   NUMERIC(5,2) DEFAULT 0.00
);

COMMENT ON TABLE public.student_details IS 'Role-specific extension for students. 1:1 with users where role = student.';


-- ── 2.3 Teacher Details (extension for role = teacher) ──────────────────────

CREATE TABLE IF NOT EXISTS public.teacher_details (
    user_id        UUID REFERENCES public.users(id) ON DELETE CASCADE PRIMARY KEY,
    faculty_code   TEXT UNIQUE,
    designation    TEXT,
    specialization TEXT,
    joining_date   DATE
);

COMMENT ON TABLE public.teacher_details IS 'Role-specific extension for teachers. 1:1 with users where role = teacher.';


-- ── 2.4 Admin Details (extension for role = admin) ──────────────────────────

CREATE TABLE IF NOT EXISTS public.admin_details (
    user_id          UUID REFERENCES public.users(id) ON DELETE CASCADE PRIMARY KEY,
    permission_scope TEXT DEFAULT 'full',
    managed_branches TEXT[]
);

COMMENT ON TABLE public.admin_details IS 'Role-specific extension for admins. Thin now — ready for multi-admin scoped permissions.';


-- ── 2.5 Courses ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.courses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key    TEXT UNIQUE,
    source        TEXT DEFAULT 'manual' CHECK (source IN ('manual', 'timetable')),
    department    TEXT,                            -- Legacy (kept for backward compat)
    branch        TEXT,                            -- Preferred over department
    semester      TEXT,
    term          TEXT,
    course_name   TEXT NOT NULL,
    course_code   TEXT NOT NULL,
    teacher       TEXT,
    schedule      TEXT,
    room          TEXT,
    student_count INT DEFAULT 0,
    status        TEXT DEFAULT 'active'
);


-- ── 2.6 Timetable Entries ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.timetable_entries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key   TEXT UNIQUE NOT NULL,
    entry_id     TEXT,
    course_id    BIGINT REFERENCES public.courses(id) ON DELETE SET NULL,
    department   TEXT NOT NULL,                    -- Legacy
    branch       TEXT,                             -- Preferred
    semester     TEXT NOT NULL,
    term         TEXT,
    day_of_week  TEXT NOT NULL CHECK (day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday')),
    start_time   TIME NOT NULL,
    end_time     TIME NOT NULL,
    course_code  TEXT NOT NULL,
    course_title TEXT NOT NULL,
    faculty_code TEXT,
    faculty_name TEXT,
    room_lab     TEXT,
    batch_group  TEXT,
    class_type   TEXT,
    notes        TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS timetable_entries_program_idx
    ON public.timetable_entries (department, semester, day_of_week, start_time);
CREATE INDEX IF NOT EXISTS timetable_entries_branch_idx
    ON public.timetable_entries (branch, semester, day_of_week, start_time);
CREATE INDEX IF NOT EXISTS timetable_entries_course_id_idx
    ON public.timetable_entries (course_id);


-- ── 2.7 Enrollments (replaces course_instructors + implicit student-course) ─

CREATE TABLE IF NOT EXISTS public.enrollments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    course_id      BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    role_in_course TEXT NOT NULL CHECK (role_in_course IN ('student', 'instructor')),
    enrolled_at    TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, course_id)
);

COMMENT ON TABLE public.enrollments IS 'Unified course enrollment for both students and teachers. Replaces old course_instructors table.';


-- ── 2.8 Attendance ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.attendance (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- New (preferred) FK
    user_id                UUID REFERENCES public.users(id) ON DELETE CASCADE,
    -- Legacy FK (kept until full migration completes)
    student_id             BIGINT REFERENCES public.students(id),
    course_id              BIGINT REFERENCES public.courses(id),
    timetable_course_code  TEXT,
    timetable_course_name  TEXT,
    department             TEXT,                    -- Legacy
    branch                 TEXT,                    -- Preferred
    semester               TEXT,
    date_attended          DATE NOT NULL DEFAULT CURRENT_DATE,
    time_attended          TIME,
    status                 TEXT DEFAULT 'absent' CHECK (status IN ('present', 'absent', 'late')),
    -- New enrichment columns
    marked_by              UUID REFERENCES public.users(id) ON DELETE SET NULL,
    source                 TEXT DEFAULT 'manual' CHECK (source IN ('face_recognition', 'manual', 'bulk_import')),
    confidence             NUMERIC(5,2),
    marked_at              TIMESTAMPTZ DEFAULT NOW(),
    -- Uniqueness constraints
    UNIQUE (student_id, course_id, date_attended),
    UNIQUE (student_id, timetable_course_code, department, semester, date_attended)
);

COMMENT ON COLUMN public.attendance.marked_by IS 'Teacher or face engine user who marked this record.';
COMMENT ON COLUMN public.attendance.source IS 'How attendance was recorded: face_recognition, manual, or bulk_import.';
COMMENT ON COLUMN public.attendance.confidence IS 'Face recognition confidence score (NULL if manual entry).';


-- ── 2.9 Face Embeddings (replaces filesystem .npy/.pkl files) ───────────────

CREATE TABLE IF NOT EXISTS public.face_embeddings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    embedding     FLOAT8[] NOT NULL,
    sample_count  INTEGER DEFAULT 0,
    model_version TEXT DEFAULT 'haar_knn_v1',
    enrolled_at   TIMESTAMPTZ DEFAULT NOW(),
    is_active     BOOLEAN DEFAULT true
);

COMMENT ON TABLE public.face_embeddings IS 'Durable store for face recognition data. Python engine loads into memory at startup.';


-- ── 2.10 Activity Logs ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID REFERENCES public.users(id) ON DELETE SET NULL,
    action      TEXT NOT NULL,                     -- e.g. 'login', 'mark_attendance', 'approve_student'
    entity_type TEXT,                              -- e.g. 'student', 'course', 'attendance'
    entity_id   TEXT,
    details     JSONB,
    ip_address  TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_logs_user_time
    ON public.activity_logs(user_id, created_at DESC);


-- ════════════════════════════════════════════════════════════════════════════
-- 3. LEGACY TABLES (kept for backward compatibility — will be dropped after
--    full migration of backend controllers + frontend pages)
-- ════════════════════════════════════════════════════════════════════════════

-- ── 3.1 Profiles (legacy — replaced by users table) ─────────────────────────

CREATE TABLE IF NOT EXISTS public.profiles (
    id              UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    role            user_role DEFAULT 'student' NOT NULL,
    email           TEXT,
    full_name       TEXT,
    phone           TEXT,
    student_id      TEXT,                          -- SBRN
    department      TEXT,                          -- Legacy
    branch          TEXT,                          -- Preferred
    semester        INTEGER CHECK (semester BETWEEN 1 AND 8),
    section         TEXT,                          -- Legacy
    session         TEXT,                          -- Preferred
    profile_image   TEXT,
    approval_status TEXT NOT NULL DEFAULT 'approved'
                    CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    face_enrolled   BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS profiles_student_id_unique
    ON public.profiles (student_id)
    WHERE student_id IS NOT NULL;


-- ── 3.2 Students (legacy — replaced by users + student_details) ─────────────

CREATE TABLE IF NOT EXISTS public.students (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id_text   TEXT UNIQUE,                 -- The SBRN (e.g. 2024CE001)
    name              TEXT NOT NULL,
    email             TEXT UNIQUE NOT NULL,
    course            TEXT,
    department        TEXT,                         -- Legacy
    branch            TEXT,                         -- Preferred
    semester          INT CHECK (semester BETWEEN 1 AND 8),
    section           TEXT,                         -- Legacy
    session           TEXT,                         -- Preferred
    phone             TEXT,
    face_enrolled     BOOLEAN DEFAULT FALSE,
    status            TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    attendance_rate   FLOAT DEFAULT 0,
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE
);


-- ── 3.3 Instructors (legacy — replaced by users + teacher_details) ──────────

CREATE TABLE IF NOT EXISTS public.instructors (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
);


-- ── 3.4 Course Instructors (legacy — replaced by enrollments) ───────────────

CREATE TABLE IF NOT EXISTS public.course_instructors (
    course_id     BIGINT REFERENCES public.courses(id),
    instructor_id BIGINT REFERENCES public.instructors(id),
    PRIMARY KEY (course_id, instructor_id)
);


-- ════════════════════════════════════════════════════════════════════════════
-- 4. FUNCTIONS
-- ════════════════════════════════════════════════════════════════════════════

-- ── 4.1 get_my_role() — returns the current user's role from the users table ─

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS user_role
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN (SELECT role FROM public.users WHERE id = auth.uid());
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_my_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_role() TO service_role;


-- ── 4.2 handle_new_user() — auto-populate users + extension table on signup ──

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_role user_role;
BEGIN
    v_role := COALESCE(new.raw_user_meta_data->>'role', 'student')::user_role;

    -- Insert into base users table
    INSERT INTO public.users (
        id, email, role, full_name, branch, phone, approval_status, created_at
    )
    VALUES (
        new.id,
        new.email,
        v_role,
        COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'branch', new.raw_user_meta_data->>'department'),
        new.raw_user_meta_data->>'phone',
        COALESCE(new.raw_user_meta_data->>'approval_status', 'approved'),
        NOW()
    )
    ON CONFLICT (id) DO UPDATE SET
        full_name       = EXCLUDED.full_name,
        branch          = EXCLUDED.branch,
        phone           = EXCLUDED.phone,
        approval_status = EXCLUDED.approval_status;

    -- Insert into role-specific extension table
    IF v_role = 'student' THEN
        INSERT INTO public.student_details (
            user_id, sbrn, semester, session
        ) VALUES (
            new.id,
            new.raw_user_meta_data->>'student_id',
            NULLIF(new.raw_user_meta_data->>'semester', '')::INTEGER,
            new.raw_user_meta_data->>'session'
        )
        ON CONFLICT (user_id) DO UPDATE SET
            sbrn     = EXCLUDED.sbrn,
            semester = EXCLUDED.semester,
            session  = EXCLUDED.session;

    ELSIF v_role = 'teacher' THEN
        INSERT INTO public.teacher_details (user_id)
        VALUES (new.id)
        ON CONFLICT DO NOTHING;

    ELSIF v_role = 'admin' THEN
        INSERT INTO public.admin_details (user_id)
        VALUES (new.id)
        ON CONFLICT DO NOTHING;
    END IF;

    RETURN new;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;


-- ── 4.3 Auth Trigger ────────────────────────────────────────────────────────

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ════════════════════════════════════════════════════════════════════════════
-- 5. ROW LEVEL SECURITY (RLS)
-- ════════════════════════════════════════════════════════════════════════════

-- Enable RLS on all tables
ALTER TABLE public.users             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_details   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_details   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_details     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.face_embeddings   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timetable_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instructors       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_instructors ENABLE ROW LEVEL SECURITY;

-- ── Cleanup existing policies ───────────────────────────────────────────────

DO $$
DECLARE
    pol RECORD;
BEGIN
    FOR pol IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', pol.policyname, pol.tablename);
    END LOOP;
END $$;

-- ── 5.1 Users Table Policies ────────────────────────────────────────────────

CREATE POLICY "Users read own"
    ON public.users FOR SELECT
    USING (id = auth.uid());

CREATE POLICY "Admins manage all users"
    ON public.users FOR ALL TO authenticated
    USING (get_my_role() = 'admin');

CREATE POLICY "Teachers read enrolled students"
    ON public.users FOR SELECT TO authenticated
    USING (
        get_my_role() = 'teacher'
        AND id IN (
            SELECT e.user_id FROM public.enrollments e
            WHERE e.course_id IN (
                SELECT e2.course_id FROM public.enrollments e2
                WHERE e2.user_id = auth.uid() AND e2.role_in_course = 'instructor'
            )
        )
    );

-- ── 5.2 Extension Table Policies ────────────────────────────────────────────

-- Student Details
CREATE POLICY "Read own student details"
    ON public.student_details FOR SELECT
    USING (user_id = auth.uid());
CREATE POLICY "Admins manage all student details"
    ON public.student_details FOR ALL TO authenticated
    USING (get_my_role() = 'admin');

-- Teacher Details
CREATE POLICY "Read own teacher details"
    ON public.teacher_details FOR SELECT
    USING (user_id = auth.uid());
CREATE POLICY "Admins manage all teacher details"
    ON public.teacher_details FOR ALL TO authenticated
    USING (get_my_role() = 'admin');

-- Admin Details
CREATE POLICY "Read own admin details"
    ON public.admin_details FOR SELECT
    USING (user_id = auth.uid());

-- ── 5.3 Courses Policies ────────────────────────────────────────────────────

CREATE POLICY "Admin All courses"
    ON public.courses FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teacher Select courses"
    ON public.courses FOR SELECT TO authenticated
    USING (get_my_role() = 'teacher');
CREATE POLICY "Student Select courses"
    ON public.courses FOR SELECT TO authenticated
    USING (get_my_role() = 'student');

-- ── 5.4 Timetable Policies ──────────────────────────────────────────────────

CREATE POLICY "Admin All timetable_entries"
    ON public.timetable_entries FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teacher Select timetable_entries"
    ON public.timetable_entries FOR SELECT TO authenticated
    USING (get_my_role() = 'teacher');
CREATE POLICY "Student Select timetable_entries"
    ON public.timetable_entries FOR SELECT TO authenticated
    USING (get_my_role() = 'student');

-- ── 5.5 Enrollments Policies ────────────────────────────────────────────────

CREATE POLICY "Read own enrollments"
    ON public.enrollments FOR SELECT
    USING (user_id = auth.uid());
CREATE POLICY "Admins manage all enrollments"
    ON public.enrollments FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teachers read course enrollments"
    ON public.enrollments FOR SELECT TO authenticated
    USING (
        get_my_role() = 'teacher'
        AND course_id IN (
            SELECT course_id FROM public.enrollments
            WHERE user_id = auth.uid() AND role_in_course = 'instructor'
        )
    );

-- ── 5.6 Attendance Policies ─────────────────────────────────────────────────

CREATE POLICY "Admin All attendance"
    ON public.attendance FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teacher Select attendance"
    ON public.attendance FOR SELECT TO authenticated
    USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Insert attendance"
    ON public.attendance FOR INSERT TO authenticated
    WITH CHECK (get_my_role() = 'teacher');
CREATE POLICY "Teacher Update attendance"
    ON public.attendance FOR UPDATE TO authenticated
    USING (get_my_role() = 'teacher');
CREATE POLICY "Student Select own attendance"
    ON public.attendance FOR SELECT TO authenticated
    USING (
        get_my_role() = 'student'
        AND (
            user_id = auth.uid()
            OR student_id IN (SELECT id FROM public.students WHERE email = auth.jwt() ->> 'email')
        )
    );

-- ── 5.7 Face Embeddings Policies ────────────────────────────────────────────

CREATE POLICY "Admins manage face embeddings"
    ON public.face_embeddings FOR ALL TO authenticated
    USING (get_my_role() = 'admin');

-- ── 5.8 Activity Logs Policies ──────────────────────────────────────────────

CREATE POLICY "Admins read activity logs"
    ON public.activity_logs FOR ALL TO authenticated
    USING (get_my_role() = 'admin');

-- ── 5.9 Legacy Table Policies ───────────────────────────────────────────────

-- Profiles (legacy)
CREATE POLICY "Admin All profiles"
    ON public.profiles FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teacher Select profiles"
    ON public.profiles FOR SELECT TO authenticated
    USING (get_my_role() = 'teacher');
CREATE POLICY "Student Select own profile"
    ON public.profiles FOR SELECT TO authenticated
    USING (auth.uid() = id);

-- Students (legacy)
CREATE POLICY "Admin All students"
    ON public.students FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teacher Select students"
    ON public.students FOR SELECT TO authenticated
    USING (get_my_role() = 'teacher');
CREATE POLICY "Student Select own record"
    ON public.students FOR SELECT TO authenticated
    USING (get_my_role() = 'student' AND email = auth.jwt() ->> 'email');

-- Instructors (legacy)
CREATE POLICY "Admin All instructors"
    ON public.instructors FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teacher Select instructors"
    ON public.instructors FOR SELECT TO authenticated
    USING (get_my_role() = 'teacher');

-- Course Instructors (legacy)
CREATE POLICY "Admin All course_instructors"
    ON public.course_instructors FOR ALL TO authenticated
    USING (get_my_role() = 'admin');
CREATE POLICY "Teacher Select course_instructors"
    ON public.course_instructors FOR SELECT TO authenticated
    USING (get_my_role() = 'teacher');


-- ════════════════════════════════════════════════════════════════════════════
-- 6. DATA MIGRATION (idempotent — safe to re-run)
-- ════════════════════════════════════════════════════════════════════════════

-- Backfill users from existing profiles
INSERT INTO public.users (id, role, email, full_name, phone, avatar_url, branch, approval_status, created_at, updated_at)
SELECT
    p.id,
    p.role,
    p.email,
    COALESCE(p.full_name, split_part(p.email, '@', 1)),
    p.phone,
    p.profile_image,
    p.branch,
    COALESCE(p.approval_status, 'approved'),
    COALESCE(p.created_at, NOW()),
    NOW()
FROM public.profiles p
ON CONFLICT (id) DO UPDATE SET
    role      = EXCLUDED.role,
    email     = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    branch    = EXCLUDED.branch;

-- Backfill student_details from profiles + students
INSERT INTO public.student_details (user_id, sbrn, semester, session, registration_date, attendance_rate)
SELECT
    p.id,
    p.student_id,
    p.semester,
    p.session,
    s.registration_date,
    s.attendance_rate
FROM public.profiles p
JOIN public.students s ON p.student_id = s.student_id_text OR p.email = s.email
WHERE p.role = 'student' AND p.student_id IS NOT NULL
ON CONFLICT (user_id) DO NOTHING;

-- Backfill teacher_details from profiles
INSERT INTO public.teacher_details (user_id)
SELECT p.id
FROM public.profiles p
WHERE p.role = 'teacher'
ON CONFLICT (user_id) DO NOTHING;

-- Backfill enrollments from course_instructors
INSERT INTO public.enrollments (user_id, course_id, role_in_course)
SELECT p.id, ci.course_id, 'instructor'
FROM public.course_instructors ci
JOIN public.instructors i ON ci.instructor_id = i.id
JOIN public.profiles p ON p.email = i.email
ON CONFLICT (user_id, course_id) DO NOTHING;

-- Backfill enrollments from attendance (implicit student-course relationship)
INSERT INTO public.enrollments (user_id, course_id, role_in_course)
SELECT DISTINCT p.id, a.course_id, 'student'
FROM public.attendance a
JOIN public.students s ON a.student_id = s.id
JOIN public.profiles p ON (p.student_id = s.student_id_text OR p.email = s.email)
ON CONFLICT (user_id, course_id) DO NOTHING;

-- Backfill user_id in attendance table
UPDATE public.attendance a
SET user_id = p.id
FROM public.students s
JOIN public.profiles p ON (p.student_id = s.student_id_text OR p.email = s.email)
WHERE a.student_id = s.id AND a.user_id IS NULL;


-- ════════════════════════════════════════════════════════════════════════════
-- 7. SCHEMA SUMMARY (for reference)
-- ════════════════════════════════════════════════════════════════════════════
--
-- ┌──────────────────────────────────────────────────────────────────────┐
-- │                        auth.users (Supabase)                        │
-- │                   Handles: passwords, JWT, sessions                 │
-- └─────────────────────────────┬────────────────────────────────────────┘
--                               │ UUID (1:1)
--                               ▼
-- ┌──────────────────────────────────────────────────────────────────────┐
-- │                          users (base)                                │
-- │    id · role · email · full_name · branch · approval_status          │
-- ├──────────┬───────────────┬───────────────┬──────────────────────────┤
-- │    ┌─────▼──────┐  ┌─────▼──────┐  ┌─────▼──────┐                  │
-- │    │ student_   │  │ teacher_   │  │ admin_     │   Extension       │
-- │    │ details    │  │ details    │  │ details    │   Tables          │
-- │    │ sbrn       │  │ faculty_   │  │ permission │                   │
-- │    │ semester   │  │ code       │  │ _scope     │                   │
-- │    │ session    │  │ designation│  │ managed_   │                   │
-- │    │ att_rate   │  │ spec.      │  │ branches   │                   │
-- │    └────────────┘  └────────────┘  └────────────┘                   │
-- │          │                                                          │
-- │    ┌─────▼────────────┐                                             │
-- │    │ face_embeddings  │                                             │
-- │    │ embedding[]      │                                             │
-- │    │ model_version    │                                             │
-- │    └──────────────────┘                                             │
-- └──────┬───────────────────────┬──────────────────────────────────────┘
--        │                       │
--        ▼                       ▼
-- ┌──────────────┐     ┌─────────────────┐     ┌─────────────────┐
-- │ enrollments  │────▶│    courses       │◀────│ timetable_      │
-- │ user_id      │     │ code · name      │     │ entries          │
-- │ course_id    │     │ branch · semester │     │ day · time       │
-- │ role_in_     │     └────────┬─────────┘     │ room             │
-- │ course       │              │               └─────────────────┘
-- └──────┬───────┘              │
--        │              ┌───────▼────────┐
--        └─────────────▶│  attendance    │
--                       │ user_id        │
--                       │ course_id      │
--                       │ date · status  │
--                       │ source · conf. │
--                       └────────────────┘
--
--                       ┌────────────────┐
--                       │ activity_logs  │
--                       │ user_id        │
--                       │ action · JSONB │
--                       └────────────────┘
--
-- Legacy tables (profiles, students, instructors, course_instructors) are
-- still present for backward compatibility. They will be dropped once all
-- backend controllers and frontend pages are migrated to use the new schema.
-- ════════════════════════════════════════════════════════════════════════════
