-- Attendance Management System Database Schema (PostgreSQL/Supabase compatible)

-- ── 1. CORE TABLES ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id_text TEXT UNIQUE, -- The "STU-001" style ID
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    course TEXT,                -- Added for frontend compatibility
    face_enrolled BOOLEAN DEFAULT FALSE, 
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    attendance_rate FLOAT DEFAULT 0,
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT UNIQUE,
    source TEXT DEFAULT 'manual' CHECK (source IN ('manual', 'timetable')),
    department TEXT,
    semester TEXT,
    term TEXT,
    course_name TEXT NOT NULL,
    course_code TEXT NOT NULL,
    teacher TEXT,
    schedule TEXT,
    room TEXT,
    student_count INT DEFAULT 0,
    status TEXT DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS timetable_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT UNIQUE NOT NULL,
    entry_id TEXT,
    course_id BIGINT REFERENCES courses(id) ON DELETE SET NULL,
    department TEXT NOT NULL,
    semester TEXT NOT NULL,
    term TEXT,
    day_of_week TEXT NOT NULL CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    course_code TEXT NOT NULL,
    course_title TEXT NOT NULL,
    faculty_code TEXT,
    faculty_name TEXT,
    room_lab TEXT,
    batch_group TEXT,
    class_type TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id),
    course_id BIGINT REFERENCES courses(id),
    timetable_course_code TEXT,
    timetable_course_name TEXT,
    department TEXT,
    semester TEXT,
    date_attended DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'absent' CHECK (status IN ('present', 'absent', 'late')),
    UNIQUE (student_id, course_id, date_attended),
    UNIQUE (student_id, timetable_course_code, department, semester, date_attended)
);

CREATE TABLE IF NOT EXISTS instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS course_instructors (
    course_id BIGINT REFERENCES courses(id),
    instructor_id BIGINT REFERENCES instructors(id),
    PRIMARY KEY (course_id, instructor_id)
);

-- ── 2. SECURITY & ROLES ───────────────────────────────────────────────────────

-- Create the secure role type
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'teacher', 'student');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create the profiles table to store secure roles
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    role user_role DEFAULT 'student' NOT NULL,
    email TEXT
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Helper function to get current user's role securely
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS user_role 
LANGUAGE plpgsql 
STABLE 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN (SELECT role FROM public.profiles WHERE id = auth.uid());
END;
$$;

-- Restrict execution permissions
REVOKE EXECUTE ON FUNCTION public.get_my_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_role() TO service_role;

-- Function to handle new user signups from Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger 
LANGUAGE plpgsql 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'role', 'student')::user_role
  );
  RETURN new;
END;
$$;

-- Restrict execution permissions (Trigger functions usually only need system access)
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;

-- Trigger to call the function on every auth signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ── 3. ROW LEVEL SECURITY (RLS) POLICIES ──────────────────────────────────────

-- Enable RLS on all tables
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE timetable_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE instructors ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_instructors ENABLE ROW LEVEL SECURITY;

-- Cleanup existing policies to prevent "Already Exists" errors
DO $$ 
DECLARE
    pol RECORD;
BEGIN
    FOR pol IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') 
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', pol.policyname, pol.tablename);
    END LOOP;
END $$;

-- ADMIN POLICIES (Can do everything)
CREATE POLICY "Admin All students" ON students FOR ALL TO authenticated USING (get_my_role() = 'admin');
CREATE POLICY "Admin All courses" ON courses FOR ALL TO authenticated USING (get_my_role() = 'admin');
CREATE POLICY "Admin All timetable_entries" ON timetable_entries FOR ALL TO authenticated USING (get_my_role() = 'admin');
CREATE POLICY "Admin All attendance" ON attendance FOR ALL TO authenticated USING (get_my_role() = 'admin');
CREATE POLICY "Admin All instructors" ON instructors FOR ALL TO authenticated USING (get_my_role() = 'admin');
CREATE POLICY "Admin All course_instructors" ON course_instructors FOR ALL TO authenticated USING (get_my_role() = 'admin');
CREATE POLICY "Admin All profiles" ON public.profiles FOR ALL TO authenticated USING (get_my_role() = 'admin');

-- TEACHER POLICIES
CREATE POLICY "Teacher Select courses" ON courses FOR SELECT TO authenticated USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Select timetable_entries" ON timetable_entries FOR SELECT TO authenticated USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Select students" ON students FOR SELECT TO authenticated USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Select attendance" ON attendance FOR SELECT TO authenticated USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Insert attendance" ON attendance FOR INSERT TO authenticated WITH CHECK (get_my_role() = 'teacher');
CREATE POLICY "Teacher Update attendance" ON attendance FOR UPDATE TO authenticated USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Select instructors" ON instructors FOR SELECT TO authenticated USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Select course_instructors" ON course_instructors FOR SELECT TO authenticated USING (get_my_role() = 'teacher');
CREATE POLICY "Teacher Select profiles" ON public.profiles FOR SELECT TO authenticated USING (get_my_role() = 'teacher');

-- STUDENT POLICIES
CREATE POLICY "Student Select own record" ON students FOR SELECT TO authenticated 
USING (get_my_role() = 'student' AND email = auth.jwt() ->> 'email');

CREATE POLICY "Student Select own attendance" ON attendance FOR SELECT TO authenticated 
USING (
  get_my_role() = 'student' AND 
  student_id IN (SELECT id FROM students WHERE email = auth.jwt() ->> 'email')
);

CREATE POLICY "Student Select courses" ON courses FOR SELECT TO authenticated USING (get_my_role() = 'student');
CREATE POLICY "Student Select timetable_entries" ON timetable_entries FOR SELECT TO authenticated USING (get_my_role() = 'student');
CREATE POLICY "Student Select own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);

-- ── 4. INITIAL DATA MIGRATION ────────────────────────────────────────────────

-- Populate profiles table for any existing auth users
INSERT INTO public.profiles (id, email, role)
SELECT 
    id, 
    email, 
    CASE 
        WHEN raw_user_meta_data->>'role' = 'admin' THEN 'admin'::user_role
        WHEN raw_user_meta_data->>'role' = 'teacher' THEN 'teacher'::user_role
        ELSE 'student'::user_role
    END
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- ── 5. CRON JOBS (WEEKLY DIGEST) ─────────────────────────────────────────────
-- Requires pg_cron extension to be enabled in Supabase Dashboard.
-- This schedules the 'weekly-digest' edge function to run every Monday at 08:00 AM.
-- Replace project-ref with the actual project reference if running in production.

-- Note: To fully activate this, the pg_net extension is required:
-- CREATE EXTENSION IF NOT EXISTS pg_net;
-- 
-- SELECT cron.schedule(
--   'weekly-attendance-digest',
--   '0 8 * * 1', -- Every Monday at 8:00 AM
--   $$
--   SELECT net.http_post(
--       url:='https://lngcsgcqtwdgyrvmykhy.supabase.co/functions/v1/weekly-digest',
--       headers:='{"Content-Type": "application/json", "Authorization": "Bearer YOUR_ANON_KEY"}'::jsonb
--   );
--   $$
-- );
