-- Attendance Management System Database Schema (PostgreSQL/Supabase compatible)

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id_text TEXT UNIQUE, -- The "STU-001" style ID
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    course TEXT,                -- Added for frontend compatibility
    face_enrolled BOOLEAN DEFAULT FALSE, -- Added for frontend compatibility
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive')), -- Added for frontend compatibility
    attendance_rate FLOAT DEFAULT 0, -- Added for frontend compatibility
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name TEXT NOT NULL,
    course_code TEXT UNIQUE NOT NULL,
    teacher TEXT,
    schedule TEXT,
    room TEXT,
    student_count INT DEFAULT 0,
    status TEXT DEFAULT 'active'
);

CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id),
    course_id BIGINT REFERENCES courses(id),
    date_attended DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'absent' CHECK (status IN ('present', 'absent', 'late')),
    UNIQUE (student_id, course_id, date_attended)
);

CREATE TABLE instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
);

CREATE TABLE course_instructors (
    course_id BIGINT REFERENCES courses(id),
    instructor_id BIGINT REFERENCES instructors(id),
    PRIMARY KEY (course_id, instructor_id)
);

-- Security: Row Level Security (RLS)
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE instructors ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_instructors ENABLE ROW LEVEL SECURITY;

-- Drop existing basic policies if any (in case this is re-run)
DROP POLICY IF EXISTS "Allow authenticated read access" ON students;
DROP POLICY IF EXISTS "Allow authenticated read access" ON courses;
DROP POLICY IF EXISTS "Allow authenticated read access" ON attendance;
DROP POLICY IF EXISTS "Allow authenticated read access" ON instructors;
DROP POLICY IF EXISTS "Allow authenticated read access" ON course_instructors;
DROP POLICY IF EXISTS "Allow authenticated insert attendance" ON attendance;

-- ADMIN POLICIES (Can do everything)
CREATE POLICY "Admin All students" ON students FOR ALL TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'admin');
CREATE POLICY "Admin All courses" ON courses FOR ALL TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'admin');
CREATE POLICY "Admin All attendance" ON attendance FOR ALL TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'admin');
CREATE POLICY "Admin All instructors" ON instructors FOR ALL TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'admin');
CREATE POLICY "Admin All course_instructors" ON course_instructors FOR ALL TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'admin');

-- TEACHER POLICIES (Can read courses, students, and attendance. Can insert/update attendance)
CREATE POLICY "Teacher Select courses" ON courses FOR SELECT TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'teacher');
CREATE POLICY "Teacher Select students" ON students FOR SELECT TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'teacher');
CREATE POLICY "Teacher Select attendance" ON attendance FOR SELECT TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'teacher');
CREATE POLICY "Teacher Insert attendance" ON attendance FOR INSERT TO authenticated WITH CHECK (auth.jwt() -> 'user_metadata' ->> 'role' = 'teacher');
CREATE POLICY "Teacher Update attendance" ON attendance FOR UPDATE TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'teacher');
CREATE POLICY "Teacher Select instructors" ON instructors FOR SELECT TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'teacher');
CREATE POLICY "Teacher Select course_instructors" ON course_instructors FOR SELECT TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'teacher');

-- STUDENT POLICIES (Can read their own student record and attendance)
CREATE POLICY "Student Select own record" ON students FOR SELECT TO authenticated 
USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'student' AND email = auth.jwt() ->> 'email');

CREATE POLICY "Student Select own attendance" ON attendance FOR SELECT TO authenticated 
USING (
  auth.jwt() -> 'user_metadata' ->> 'role' = 'student' AND 
  student_id IN (SELECT id FROM students WHERE email = auth.jwt() ->> 'email')
);

CREATE POLICY "Student Select courses" ON courses FOR SELECT TO authenticated USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'student');
