-- ============================================================================
-- Migration: Database Restructure (Base + Extension Tables)
-- Creates unified users table and role-specific extension tables.
-- Migrates data from profiles, students, instructors.
-- ============================================================================

-- ── 1. Create Base and Extension Tables ──────────────────────────────────────

-- Base Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    role user_role NOT NULL,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    phone TEXT,
    avatar_url TEXT,
    branch TEXT,
    approval_status TEXT NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Student Details
CREATE TABLE IF NOT EXISTS public.student_details (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE PRIMARY KEY,
    sbrn TEXT NOT NULL UNIQUE,
    semester INTEGER NOT NULL CHECK (semester BETWEEN 1 AND 8),
    session TEXT NOT NULL,
    section TEXT,
    registration_date DATE DEFAULT CURRENT_DATE,
    attendance_rate NUMERIC(5,2) DEFAULT 0.00
);

-- Teacher Details
CREATE TABLE IF NOT EXISTS public.teacher_details (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE PRIMARY KEY,
    faculty_code TEXT UNIQUE,
    designation TEXT,
    specialization TEXT,
    joining_date DATE
);

-- Admin Details
CREATE TABLE IF NOT EXISTS public.admin_details (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE PRIMARY KEY,
    permission_scope TEXT DEFAULT 'full',
    managed_branches TEXT[]
);

-- Face Embeddings
CREATE TABLE IF NOT EXISTS public.face_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    embedding FLOAT8[] NOT NULL,
    sample_count INTEGER DEFAULT 0,
    model_version TEXT DEFAULT 'haar_knn_v1',
    enrolled_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

-- Enrollments
CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    role_in_course TEXT NOT NULL CHECK (role_in_course IN ('student', 'instructor')),
    enrolled_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, course_id)
);

-- Activity Logs
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    details JSONB,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_logs_user_time ON public.activity_logs(user_id, created_at DESC);

-- ── 2. Data Migration ────────────────────────────────────────────────────────

-- We need to ensure we migrate existing profiles into `users`.
-- Because we need full_name, we'll try to extract it from auth.users or profiles if possible.

INSERT INTO public.users (id, role, email, full_name, phone, avatar_url, branch, approval_status, created_at, updated_at)
SELECT 
    p.id, 
    p.role, 
    p.email, 
    COALESCE(p.full_name, split_part(p.email, '@', 1)), -- fallback if full_name is null
    p.phone, 
    p.profile_image, 
    p.branch, 
    COALESCE(p.approval_status, 'approved'), 
    COALESCE(p.created_at, NOW()), 
    NOW()
FROM public.profiles p
ON CONFLICT (id) DO UPDATE SET
    role = EXCLUDED.role,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    branch = EXCLUDED.branch;

-- Migrate Student Details
INSERT INTO public.student_details (user_id, sbrn, semester, session, registration_date, attendance_rate)
SELECT 
    p.id,
    p.student_id, -- assuming student_id is the SBRN in profiles
    p.semester,
    p.session,
    s.registration_date,
    s.attendance_rate
FROM public.profiles p
JOIN public.students s ON p.student_id = s.student_id_text OR p.email = s.email
WHERE p.role = 'student' AND p.student_id IS NOT NULL
ON CONFLICT (user_id) DO NOTHING;

-- Migrate Teacher Details
-- The existing DB has an `instructors` table with `name` and `email`.
INSERT INTO public.teacher_details (user_id)
SELECT p.id
FROM public.profiles p
WHERE p.role = 'teacher'
ON CONFLICT (user_id) DO NOTHING;

-- Migrate Enrollments for Instructors
INSERT INTO public.enrollments (user_id, course_id, role_in_course)
SELECT p.id, ci.course_id, 'instructor'
FROM public.course_instructors ci
JOIN public.instructors i ON ci.instructor_id = i.id
JOIN public.profiles p ON p.email = i.email
ON CONFLICT (user_id, course_id) DO NOTHING;

-- (Student enrollments are currently implicit from attendance, we can backfill them if needed)
INSERT INTO public.enrollments (user_id, course_id, role_in_course)
SELECT DISTINCT p.id, a.course_id, 'student'
FROM public.attendance a
JOIN public.students s ON a.student_id = s.id
JOIN public.profiles p ON (p.student_id = s.student_id_text OR p.email = s.email)
ON CONFLICT (user_id, course_id) DO NOTHING;

-- ── 3. Modify Attendance Table to link to Users ──────────────────────────────

-- Add new user_id column
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS marked_by UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual' CHECK (source IN ('face_recognition', 'manual', 'bulk_import'));
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS confidence NUMERIC(5,2);
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS marked_at TIMESTAMPTZ DEFAULT NOW();

-- Backfill user_id in attendance
UPDATE public.attendance a
SET user_id = p.id
FROM public.students s
JOIN public.profiles p ON (p.student_id = s.student_id_text OR p.email = s.email)
WHERE a.student_id = s.id AND a.user_id IS NULL;

-- ── 4. Update Triggers ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role user_role;
BEGIN
  v_role := COALESCE(new.raw_user_meta_data->>'role', 'student')::user_role;
  
  -- Insert into base users table
  INSERT INTO public.users (
    id, email, role, full_name, branch, phone, approval_status, created_at
  )
  VALUES (
    new.id,
    new.email,
    v_role,
    COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'branch', new.raw_user_meta_data->>'department'),
    new.raw_user_meta_data->>'phone',
    COALESCE(new.raw_user_meta_data->>'approval_status', 'approved'),
    NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name       = EXCLUDED.full_name,
    branch          = EXCLUDED.branch,
    phone           = EXCLUDED.phone,
    approval_status = EXCLUDED.approval_status;

  -- Insert into role-specific tables
  IF v_role = 'student' THEN
    INSERT INTO public.student_details (
      user_id, sbrn, semester, session
    ) VALUES (
      new.id,
      new.raw_user_meta_data->>'student_id',
      NULLIF(new.raw_user_meta_data->>'semester', '')::INTEGER,
      new.raw_user_meta_data->>'session'
    )
    ON CONFLICT (user_id) DO UPDATE SET
      sbrn     = EXCLUDED.sbrn,
      semester = EXCLUDED.semester,
      session  = EXCLUDED.session;
  ELSIF v_role = 'teacher' THEN
    INSERT INTO public.teacher_details (user_id) VALUES (new.id) ON CONFLICT DO NOTHING;
  ELSIF v_role = 'admin' THEN
    INSERT INTO public.admin_details (user_id) VALUES (new.id) ON CONFLICT DO NOTHING;
  END IF;

  RETURN new;
END;
$$;

-- ── 5. RLS Policies for New Tables ───────────────────────────────────────────

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.face_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Helper to get role from new users table
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS user_role 
LANGUAGE plpgsql 
STABLE 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN (SELECT role FROM public.users WHERE id = auth.uid());
END;
$$;

-- Users Table Policies
CREATE POLICY "Users read own" ON public.users FOR SELECT USING (id = auth.uid());
CREATE POLICY "Admins read all" ON public.users FOR SELECT USING (get_my_role() = 'admin');

-- Teachers read students in their courses
CREATE POLICY "Teachers read enrolled students" ON public.users FOR SELECT USING (
  get_my_role() = 'teacher'
  AND id IN (
    SELECT e.user_id FROM public.enrollments e
    WHERE e.course_id IN (
      SELECT e2.course_id FROM public.enrollments e2
      WHERE e2.user_id = auth.uid() AND e2.role_in_course = 'instructor'
    )
  )
);

-- Extension table policies
CREATE POLICY "Read own student details" ON public.student_details FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Admins read all student details" ON public.student_details FOR SELECT USING (get_my_role() = 'admin');

CREATE POLICY "Read own teacher details" ON public.teacher_details FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Admins read all teacher details" ON public.teacher_details FOR SELECT USING (get_my_role() = 'admin');

-- Enrollments policies
CREATE POLICY "Read own enrollments" ON public.enrollments FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Admins read all enrollments" ON public.enrollments FOR SELECT USING (get_my_role() = 'admin');
CREATE POLICY "Teachers read course enrollments" ON public.enrollments FOR SELECT USING (
  get_my_role() = 'teacher' 
  AND course_id IN (
    SELECT course_id FROM public.enrollments WHERE user_id = auth.uid() AND role_in_course = 'instructor'
  )
);
