-- Store ABVGIET timetable data as first-class database records.
-- Course codes repeat across departments/semesters, so course_code can no longer
-- be the only uniqueness boundary.

ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS source_key TEXT,
  ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS department TEXT,
  ADD COLUMN IF NOT EXISTS semester TEXT,
  ADD COLUMN IF NOT EXISTS term TEXT;

ALTER TABLE public.courses
  DROP CONSTRAINT IF EXISTS courses_course_code_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'courses_source_key_key'
      AND conrelid = 'public.courses'::regclass
  ) THEN
    ALTER TABLE public.courses
      ADD CONSTRAINT courses_source_key_key UNIQUE (source_key);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'courses_source_check'
      AND conrelid = 'public.courses'::regclass
  ) THEN
    ALTER TABLE public.courses
      ADD CONSTRAINT courses_source_check CHECK (source IN ('manual', 'timetable'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.timetable_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key TEXT UNIQUE NOT NULL,
  entry_id TEXT,
  course_id BIGINT REFERENCES public.courses(id) ON DELETE SET NULL,
  department TEXT NOT NULL,
  semester TEXT NOT NULL,
  term TEXT,
  day_of_week TEXT NOT NULL CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  course_code TEXT NOT NULL,
  course_title TEXT NOT NULL,
  faculty_code TEXT,
  faculty_name TEXT,
  room_lab TEXT,
  batch_group TEXT,
  class_type TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS timetable_entries_program_idx
  ON public.timetable_entries (department, semester, day_of_week, start_time);

CREATE INDEX IF NOT EXISTS timetable_entries_course_id_idx
  ON public.timetable_entries (course_id);

ALTER TABLE public.timetable_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin All timetable_entries" ON public.timetable_entries;
DROP POLICY IF EXISTS "Teacher Select timetable_entries" ON public.timetable_entries;
DROP POLICY IF EXISTS "Student Select timetable_entries" ON public.timetable_entries;

CREATE POLICY "Admin All timetable_entries"
  ON public.timetable_entries
  FOR ALL
  TO authenticated
  USING (get_my_role() = 'admin');

CREATE POLICY "Teacher Select timetable_entries"
  ON public.timetable_entries
  FOR SELECT
  TO authenticated
  USING (get_my_role() = 'teacher');

CREATE POLICY "Student Select timetable_entries"
  ON public.timetable_entries
  FOR SELECT
  TO authenticated
  USING (get_my_role() = 'student');

ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS timetable_course_code TEXT,
  ADD COLUMN IF NOT EXISTS timetable_course_name TEXT,
  ADD COLUMN IF NOT EXISTS department TEXT,
  ADD COLUMN IF NOT EXISTS semester TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'attendance_timetable_course_unique'
      AND conrelid = 'public.attendance'::regclass
  ) THEN
    ALTER TABLE public.attendance
      ADD CONSTRAINT attendance_timetable_course_unique
      UNIQUE (student_id, timetable_course_code, department, semester, date_attended);
  END IF;
END $$;
